service: pushyami-sls-demo


provider:
  name: aws #
  runtime: python3.6
  stage: dev
  region: us-east-1
  iamRoleStatements:
  - Effect: Allow
    Action:
      - lambda:InvokeFunction
    Resource: arn:aws:lambda:*:*:function:${self:custom.process}
  - Effect: Allow
    Action:
      - sqs:DeleteMessage
      - sqs:ReceiveMessage
    Resource: arn:aws:sqs:*:*:${self:custom.sqs}

custom:
  region: ${self:provider.region}
  stage: ${opt:stage, self:provider.stage}
  prefix: ${self:custom.stage}-${self:service}
  process: ${self:custom.prefix}-process
  sqs: ${self:custom.prefix}-messages # dev-pushyami-sls-demo-messages

package:
  exclude:
    - samle-python/**
    - sls-proj.iml

functions:
  worker:
    timeout: 10
    memorySize: 128
    handler: worker.handler
    name: ${self:custom.prefix}-process
    environment:
      sqs: ${self:custom.sqs}
      region: ${self:custom.region}
    events:
      - schedule: rate(1 minute)

resources:
  Resources:
    Messages:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.sqs}
        MessageRetentionPeriod: 1209600
        VisibilityTimeout: 60


